name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.18
      - name: build
        run: cd json && go build .
      - name: test
        run: cd json && go test -v -coverprofile=coverage.txt -covermode=atomic ./...
      - name: upload coverage
        uses: codecov/codecov-action@v2
      - name: vet
        run: cd json && go vet .

